name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master # Quando você enviar código para a master, ele publica

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Baixando o código
        uses: actions/checkout@v3

      - name: Preparando o Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalando as dependências
        run: npm install

      - name: Compilando o Frontend (Vite)
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
        run: npm run build

      - name: Publicando no GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build # Pasta que o Vite gera
